<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>RelayLink.Agent</AssemblyName>
    <RootNamespace>RelayLink.Agent</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RelayLink.Protocol/RelayLink.Protocol.csproj" />
    <ProjectReference Include="../RelayLink.Transport/RelayLink.Transport.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.2" />
  </ItemGroup>
</Project>
